
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				zombie_villager = true
				skeleton = true
				spider = true
				creeper = true
				zombie = true
				chicken = true
				item = true
				drowned = true
				squid = true
				tropical_fish = true
				dolphin = true
				chest_minecart = true
				villager = true
				minecart = true
				armor_stand = true
				bee = true
				cat = true
				experience_orb = true
				pig = true
				arrow = true
				bat = true
				husk = true
				painting = true
				parrot = true
				rabbit = true
				wolf = true
				sheep = true
				item_frame = true
				horse = true
				enderman = true
				wandering_trader = true
				trader_llama = true
				silverfish = true
				iron_golem = true
				piglin = true
				zombified_piglin = true
				small_fireball = true
				potion = true
				fireball = true
				strider = true
				blaze = true
				slime = true
				piglin_brute = true
				vindicator = true
				cave_spider = true
				vex = true
				ocelot = true
				lightning_bolt = true
				skeleton_horse = true
				cow = true
				glow_squid = true
				axolotl = true
				pufferfish = true
				elder_guardian = true
				guardian = true
				ender_pearl = true
				fox = true
				witch = true
				zombie_horse = true
				glow_item_frame = true
				evoker = true
				allay = true

			[light_sources.settings.entities.alexsmobs]
				fly = true
				leafcutter_ant = true
				underminer = true
				skelewag = true
				crow = true
				toucan = true
				snow_leopard = true
				blue_jay = true
				maned_wolf = true
				dropbear = true
				laviathan = true
				seagull = true
				tasmanian_devil = true
				capuchin_monkey = true
				potoo = true
				raccoon = true
				kangaroo = true
				elephant = true
				flying_fish = true
				centipede_head = true
				centipede_body = true
				centipede_tail = true
				skunk = true
				terrapin = true
				catfish = true
				gorilla = true
				seal = true
				hummingbird = true
				orca = true

			[light_sources.settings.entities.ars_nouveau]
				starbuncle = true
				whirlisprig = true
				wilden_stalker = true
				drygmy = true
				wilden_hunter = true
				gift_starby = true
				wilden_guardian = true
				summon_wolf = true
				spike = true
				vexing_weald_walker = true

			[light_sources.settings.entities.iter_rpg]
				goblin_warrior = true
				hobgoblin = true
				goblin = true
				water_elemental = true
				blob = true
				projectile_droplet_projectile = true
				projectile_driftbow = true
				debug_mobmorph = true
				giant_spider = true
				air_elemental = true
				spiderling = true
				fire_elemental = true
				revenant = true
				carcass = true
				demonsoul = true
				demonspine = true
				projectile_fireball_projectile = true
				scallop = true

			[light_sources.settings.entities.gothic]
				scavenger = true
				scavenger_young = true
				npc_oldcamp_hunter = true
				npc_swamp_camp_hunter = true
				stone_guardian = true
				npc_farmer = true
				molerat = true
				ice_wolf = true
				warg = true
				gothic_wolf = true

			[light_sources.settings.entities.iceandfire]
				myrmex_worker = true
				myrmex_queen = true
				myrmex_soldier = true
				myrmex_sentinel = true
				ice_dragon = true
				myrmex_egg = true
				stymphalian_bird = true
				hippocampus = true
				sea_serpent = true
				lightning_dragon = true
				hippogryph = true
				dragon_multipart = true
				deathworm = true
				fire_dragon = true
				troll = true
				pixie = true
				hydra_multipart = true
				hydra = true
				ghost = true
				multipart = true
				cyclops = true
				cylcops_multipart = true

			[light_sources.settings.entities.medieval_craft_weapons]
				archer = true
				knight = true
				soldier = true
				romanlegionary = true
				heavyknight = true
				viking_1 = true
				viking_2 = true

			[light_sources.settings.entities.born_in_chaos_v1]
				door_knight = true
				zombie_clown = true
				dark_vortex = true
				dread_hound = true
				scarlet_persecutor = true
				sir_pumpkinhead = true
				baby_skeleton = true
				zombie_clown_not_despawn = true
				skeleton_thrasher = true
				decaying_zombie = true
				decrepit_skeleton = true
				skeleton_demoman = true
				bonescaller = true
				restless_spirit = true
				baby_skeleton_2 = true
				corpse_fish = true
				corpse_fly = true
				swarmer = true
				zombie_bruiser = true
				barrel_zombie = true
				phantom_creeper = true
				wither_scuttler = true
				nightmare_stalker = true
				fallen_chaos_knight = true
				supreme_bonescaller = true
				shy_spirit = true
				mr_pumpkin = true
				projectile_staffof_magic_arrows_2 = true
				baby_skeleton_minion = true
				projectile_staffof_blindness = true
				dire_hound_leader = true
				phantom_creeper_copy = true
				bloody_gadfly = true
				spirit_guide = true
				zombie_fisherman = true
				bone_imp = true
				bone_imp_2 = true
				firelight = true
				maggot = true
				spirit_guide_assistant = true
				glutton_fish = true
				firelight_not_despawn = true
				felsteed = true
				sir_pumpkinhead_without_horse = true
				projectile_pumpkin_staff_2 = true
				sir_the_headless = true
				pumpkinhead = true
				riding_felsteed = true
				thornshell_crab = true
				decaying_zombie_not_despawn = true

			[light_sources.settings.entities.scorpions]
				emperor_scorpion = true
				brown_scorpion = true

			[light_sources.settings.entities.mekanismadditions]
				baby_skeleton = true

			[light_sources.settings.entities.villagerbrute]
				villager_brute = true

			[light_sources.settings.entities.panthalassa]
				kronosaurus = true
				anglerfish = true
				thalassomedon = true
				giant_orthocone = true
				anomalocaris = true
				coelacanth = true
				ceratodus = true
				helicoprion = true
				mosasaurus = true
				basilosaurus = true
				acrolepis = true
				archelon = true

			[light_sources.settings.entities.quark]
				shiba = true
				glass_frame = true
				foxhound = true
				forgotten = true
				toretoise = true
				stoneling = true

			[light_sources.settings.entities.dynamictrees]
				falling_tree = true

			[light_sources.settings.entities.forbidden_arcanus]
				lost_soul = true

			[light_sources.settings.entities.ylf_mod]
				ylf = true

			[light_sources.settings.entities.valhelsia_furniture]
				seat = true

			[light_sources.settings.entities.mutationcraft]
				assimilated_enderman = true
				human_stage_1 = true
				hazmat_flamethrower = true
				assimilated_human = true
				hazmat_helicopter = true
				reductor = true
				necroptor = true
				miter = true
				assimilated_spider = true
				hazmat_leader = true
				scientist = true
				hazmat_medic = true
				assimilated_pig = true
				assimilated_wandering_trader = true
				hazmat_guard = true
				assimilated_piglin = true
				human_stage_3 = true
				assimilated_witch = true
				assimilated_pillager = true
				assimilated_villager = true
				human_stage_2 = true
				assimilated_roamer = true
				assimilated_cow = true
				assimilated_horse = true
				assimilated_jockey = true
				assimilated_sheep = true

			[light_sources.settings.entities.theabyss]
				brain_walker = true
				slime_spider = true
				end_spider = true
				guard = true
				infected_wolf = true
				glow_pug = true
				infceted_cow = true
				powered_wolf = true
				mud_zombie = true
				raptor = true
				infected_spider = true
				infected_zombie = true
				shattered_zombie = true
				jelly_fish = true
				ralu_fish = true
				laro_fish = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_skeleton = true
				body_part = true
				mutant_creeper = true

			[light_sources.settings.entities.doom]
				zombieman = true
				shotgunguy = true
				possessed_worker = true
				imp = true
				spectre = true
				chaingun_mob = true
				pinky = true
				cacodemon = true
				unwilling = true
				chaingunner = true
				mechazombie = true
				barenblast = true
				revenant = true
				rocket_mob = true
				possessed_soldier = true
				tentacle = true
				prowler = true
				baron = true
				cueball = true
				mancubus = true
				fire_projectile = true
				possessed_scientist = true
				turret = true
				gargoyle = true
				archvile = true
				archvile_firing = true
				marauder = true
				whiplash = true
				summoner = true
				revenant2016 = true
				arachnotron = true
				lost_soul = true
				stone_imp = true
				armoredbaron = true
				gore_nest = true
				doom_hunter = true

			[light_sources.settings.entities.netherskeletons]
				nether_skeleton = true
				soul_skeleton = true
				charred_skeleton = true
				skelly_piglin = true
				skelly_ghast = true
				projectile_skelly_ghast = true

			[light_sources.settings.entities.magma_monsters]
				magma_monster = true
				magma_monster_grunt = true

			[light_sources.settings.entities.mutantmore]
				mutant_wither_skeleton = true
				mutant_blaze = true
				mutant_blaze_fireball = true
				fire_slash = true
				mutant_wither_skeleton_body_part = true
				mutant_blaze_rod_projectile = true
				rodling = true
				rodling_fireball = true

			[light_sources.settings.entities.vinery]
				mule = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.enhancedai]
				thrown_web = true

