#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 08 11:51:40 EDT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=13
shaderPack=SEUS-Renewed-v1.0.1.zip
enableShaders=false
